# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: prakash@880
        - name: MYSQL_DATABASE
          value: ems_ops
        - name: MYSQL_USER
          value: ems_ops
        - name: MYSQL_PASSWORD
          value: prakash@880

