apiVersion: v1
kind: Service
metadata:
  name: ems-frontend
spec:
  selector:
    app: ems-frontend
  ports:
    - protocol: TCP
      port: 3000  # The service port
      targetPort: 3000  # The target port on the pods
  type: ClusterIP
