version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front_end
    ports:
      - "3002:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back_end
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ems_ops
      MYSQL_DATABASE: ems_ops
    ports:
      - "3306:3306"
