# Build stage
FROM openjdk:17-alpine
WORKDIR /springboot-backend/
COPY /springboot-backend/target/springboot-backend-0.0.1-SNAPSHOT.jar /usr/local/lib/ems_ops.jar
EXPOSE 8080
# Specify environment variables for the database connection
ENV SPRING_DATASOURCE_URL=jdbc:mysql://ems-ops-mysql-1:3306/ems-ops-mysql?useSSL=false&allowPublicKeyRetrieval=true
ENV SPRING_DATASOURCE_USERNAME=ems_ops
ENV SPRING_DATASOURCE_PASSWORD=ems_ops
ENTRYPOINT ["java","-jar","/usr/local/lib/ems_ops.jar"]
